### good request
POST http://localhost:9005/order
Content-Type: application/json

{
  "owner": "rezrezara",
  "timestamp": 457696995,
  "ticker": "LNRD",
  "quantity": 10,
  "side": "BUY",
  "type": "LIMIT",
  "limit": 100,
  "filled": 0
}

### bas request
POST http://localhost:9005/order
Content-Type: application/json

{
"timestamp": 457696995,
"ticker": "LNRD",
"quantity": 10,
"side": "BUY",
"type": "LIMIT",
"limit": 100,
"filled": 0
}

### good request
GET http://localhost:9005/order/04c8655d-dc8f-4370-a119-e855c941f6re

###good request
PATCH http://localhost:9005/order/77aec8be-c475-4768-8f77-1883c9966019
Content-Type: application/json

{
  "filled": 44
}