### create one
POST http://localhost:9001/investor/Jacques
Content-Type: application/json

{
  "password": "123",
  "investor_data": {
  "username": "Jacques",
  "firstname": "oussama",
  "lastname": "elBoubou",
  "birthdate": "01/02/2012",
  "email": "oussama@dde"
}
}


### edit one
PUT http://localhost:9001/investor/Jacques
Content-Type: application/json

{
  "username": "Jacques",
  "firstname": "oussama",
  "lastname": "elBoubou",
  "birthdate": "01/02/2012",
  "email": "oussama@gmail.com"
}

### get one
GET http://localhost:9001/investor/Jacques

### get all
GET http://localhost:9001/investor/all


### delete one
DELETE http://localhost:9001/investor/Jacques

