###good request
POST http://localhost:9006/execute/AAPL/Jacques/Jean
Content-Type: application/json

{
  "ticker": "AAPL",
  "seller": "Jacques",
  "buyer": "Jean",
  "buy_order_guid": "8f9c9dfe-f8f3-41e7-9a51-4995823a8544",
  "sell_order_guid": "8f9c9dfe-f8f3-41e7-0000-1145823a850e",
  "quantity": 10,
  "price": 100
}